import { Hono } from "hono";
import categoryRoute from "./users/category.route.js";
import productRoute from "./users/products.route.js";
import mobileUserRoute from "./mobile/mobile-user.route.js";
import superAdminRoute from "./users/super-admin.route.js";
import storeRoute from "./users/store.route.js";
import cartRoute from "./mobile/cart.route.js";
import orderRoute from "./mobile/order.route.js";
import reportRoute from "./users/monthly-report.route.js";
import storeCategoryRoute from "./users/store_categories.route.js";
import advertisingRoute from "./users/advertising.route.js";
import productDocRoute from "./users/product-document.route.js";
import storeCateDocRoute from "./users/store-categories-document.route.js";
import storeDocRoute from "./users/store-document.route.js";
import dashboardRoute from "./users/dashboard.route.js";
import merchantRoute from "./users/merchant.route.js";
import authRoute from "./users/auth.route.js";
const HonoRoutes = new Hono();

HonoRoutes.route("/categories", categoryRoute);
HonoRoutes.route("/products", productRoute);
HonoRoutes.route("/mobile-users", mobileUserRoute);
HonoRoutes.route("/admins", superAdminRoute);
HonoRoutes.route("/stores", storeRoute);
HonoRoutes.route("/store-categories", storeCategoryRoute);
HonoRoutes.route("/carts", cartRoute);
HonoRoutes.route("/orders", orderRoute);
HonoRoutes.route("/monthly-report", reportRoute);
HonoRoutes.route("/advertisings", advertisingRoute);
HonoRoutes.route("/product-document", productDocRoute);
HonoRoutes.route("/storeCate-document", storeCateDocRoute);
HonoRoutes.route("/stores-document", storeDocRoute);
HonoRoutes.route("/dashboard", dashboardRoute);
HonoRoutes.route("/merchants", merchantRoute);
HonoRoutes.route("/auth", authRoute);
// Alias auth routes under `/users` so a single endpoint handles both super-admin and merchants
HonoRoutes.route("/users", authRoute);
export default HonoRoutes;
