import { Hono } from "hono";
import categoryRoute from "./admin/category.route.js";
import productRoute from "./admin/products.route.js";
import mobileUserRoute from "./mobile/mobile-user.route.js";
import adminUserRoute from "./admin/admin-user.route.js";
import storeRoute from "./admin/store.route.js";
import cartRoute from "./mobile/cart.route.js";
import orderRoute from "./mobile/order.route.js";
import reportRoute from "./admin/monthly-report.route.js";
const HonoRoutes = new Hono();
HonoRoutes.route("/categories", categoryRoute);
HonoRoutes.route("/products", productRoute);
HonoRoutes.route("/mobile-users", mobileUserRoute);
HonoRoutes.route("/admin-users", adminUserRoute);
HonoRoutes.route("/stores", storeRoute);
HonoRoutes.route("/carts", cartRoute);
HonoRoutes.route("/orders", orderRoute);
HonoRoutes.route("/monthly-report", reportRoute);
// HonoRoutes.route("/chats", chatRoute);
export default HonoRoutes;
