import { Hono } from "hono";
import advertisingController from "../../services/admin/advertising.service.js";
const routes = new Hono();
routes.get("/", advertisingController.getMany);
routes.post("/", advertisingController.create);
routes.get("/img/:id", advertisingController.getImage);
routes.patch("/update-img/:id", advertisingController.updateImage);
routes.patch("/update-info/:id", advertisingController.updateInfo);
routes.delete("/:id", advertisingController.delete);
routes.get("/:id", advertisingController.getById);
export default routes;
