import { Hono } from "hono";
import { merchantController } from "../../services/admin/merchant.service.js";
const routes = new Hono();
routes.get("/", merchantController.getMany);
routes.get("/search", merchantController.search);
routes.get("/overall-stats", merchantController.getMerchantOverallStats);
routes.get("/commissions", merchantController.getCommissions);
routes.post("/", merchantController.createMerchant);
routes.post("/login", merchantController.login);
routes.patch("/update-info/:id", merchantController.updateAccountInfo);
routes.patch("/update-profile/:id", merchantController.updateProfile);
routes.patch("/update-commission", merchantController.updateComission);
routes.delete("/:id", merchantController.delete);
routes.get("/profile/:id", merchantController.getProfile);
routes.get("/:id", merchantController.getMerchantDetail);
export default routes;
