import { Hono } from "hono";
import { merchantController } from "../../services/users/merchant.service.js";
import { verifyToken } from "../../middleware/authMiddleware.js";
const routes = new Hono();
routes.get("/", merchantController.getMany);
routes.get("/search", merchantController.search);
routes.get("/get-detail", verifyToken, merchantController.getMerchantDetail);
routes.get("/order-info", verifyToken, merchantController.getOrderInfo);
routes.get("/overall-stats", merchantController.getMerchantOverallStats);
routes.get("/commissions", merchantController.getCommissions);
routes.post("/", merchantController.createMerchant);
routes.post("/login", merchantController.login);
routes.get("/order-detail/:id", merchantController.getDetailOrderInfo);
routes.patch("/update-info/:id", merchantController.updateAccountInfo);
routes.patch("/update-profile/:id", merchantController.updateProfile);
routes.patch("/update-commissions/:id", merchantController.updateComission);
routes.delete("/:id", merchantController.delete);
// routes.get("/profile/:id", merchantController.getProfile);
export default routes;
