import { Hono } from "hono";
import productController from "../../services/admin/products.service.js";
const routes = new Hono();
routes.get("/", productController.getMany);
routes.get("/grouped", productController.getProductsGroupedByCategory);
routes.get("/search", productController.search);
routes.post("/", productController.create);
routes.patch("/:id", productController.update);
routes.delete("/:id", productController.delete);
routes.get("/img/:id", productController.getImage);
routes.get("/:id", productController.getById);
export default routes;
