import { Hono } from "hono";
import storeController from "../../services/admin/store.service.js";
import store from "../../models/admin/store.js";
const routes = new Hono();
routes.get("/", storeController.getMany);
routes.get("/search", storeController.search);
routes.post("/", storeController.create);
routes.patch("/:id", storeController.updateInfo);
routes.delete("/:id", storeController.delete);
routes.get("/store-image/:id", storeController.getStoreImage);
routes.get("/:id", storeController.getById);
export default routes;
